# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wWVkT1Kr6A9qoQwI0KePh1psbpQX28HJ
"""

project_id = "MIPT23"
model_version = 2
confidence = 0.7
iou_thresh = 0.5
api_key = "Kw0KYDARwdD4mRdI62VS"
tg_bot_token = 'AAHw8rq1J4b7X1P_qiKJz7EqfNnDqEltWtY'
temp = '6936392258:'