# -*- coding: utf-8 -*-
"""telegram_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IFyBOB1PIrMk7AVD_tH7fWvdKHtg7f5C
"""

import requests
import config *
from aiogram import Bot, types
from aiogram.dispatcher import Dispatcher
from aiogram.utils import executor
import base64
from PIL import Image
from io import BytesIO


bot = Bot(token=tg_bot_token)
dp = Dispatcher(bot)


@dp.message_handler(commands=["start"])
async def start_command(message: types.Message):
    await message.reply("Привет! Вставь URL фото")


@dp.message_handler()
async def find_fox(message: types.Message):

    try:
        res = requests.post(
      f"https://detect.roboflow.com/{project_id}/{model_version}?api_key={api_key}&confidence={confidence}&overlap={iou_thresh}&image={message.text}",
      )

      predictions = res.json()

        await message.reply(predictions)

    except:
        await message.reply("\U00002620 check URL \U00002620")


if __name__ == '__main__':
    executor.start_polling(dp)